export const pokemonData = [
  {
    id: 1,
    type: "Fire",
    name: "Vulpix",
    base_experience: 60,
    height: 6,
    weight: 90,
  },
  {
    id: 2,
    type: "Fire",
    name: "Growlithe",
    base_experience: 70,
    height: 7,
    weight: 190,
  },
  {
    id: 3,
    type: "Fire",
    name: "Magmar",
    base_experience: 173,
    height: 13,
    weight: 445,
  },
  {
    id: 4,
    type: "Fire",
    name: "Flareon",
    base_experience: 184,
    height: 9,
    weight: 250,
  },
  {
    id: 5,
    type: "Fire",
    name: "Rapidash",
    base_experience: 175,
    height: 17,
    weight: 950,
  },
  {
    id: 6,
    type: "Fire",
    name: "Houndoom",
    base_experience: 175,
    height: 14,
    weight: 350,
  },
  {
    id: 7,
    type: "Fire",
    name: "Torkoal",
    base_experience: 165,
    height: 5,
    weight: 804,
  },
  {
    id: 8,
    type: "Fire",
    name: "Blaziken",
    base_experience: 239,
    height: 19,
    weight: 520,
  },
  {
    id: 9,
    type: "Fire",
    name: "Infernape",
    base_experience: 240,
    height: 12,
    weight: 550,
  },
  {
    id: 10,
    type: "Fire",
    name: "Arcanine",
    base_experience: 194,
    height: 19,
    weight: 1550,
  },

  {
    id: 11,
    type: "Water",
    name: "Squirtle",
    base_experience: 64,
    height: 7,
    weight: 65,
  },
  {
    id: 12,
    type: "Water",
    name: "Psyduck",
    base_experience: 64,
    height: 8,
    weight: 196,
  },
  {
    id: 13,
    type: "Water",
    name: "Poliwag",
    base_experience: 60,
    height: 6,
    weight: 124,
  },
  {
    id: 14,
    type: "Water",
    name: "Seel",
    base_experience: 65,
    height: 11,
    weight: 900,
  },
  {
    id: 15,
    type: "Water",
    name: "Staryu",
    base_experience: 68,
    height: 8,
    weight: 345,
  },
  {
    id: 16,
    type: "Water",
    name: "Gyarados",
    base_experience: 189,
    height: 65,
    weight: 2350,
  },
  {
    id: 17,
    type: "Water",
    name: "Lapras",
    base_experience: 187,
    height: 25,
    weight: 2200,
  },
  {
    id: 18,
    type: "Water",
    name: "Vaporeon",
    base_experience: 184,
    height: 10,
    weight: 290,
  },
  {
    id: 19,
    type: "Water",
    name: "Totodile",
    base_experience: 63,
    height: 6,
    weight: 95,
  },
  {
    id: 20,
    type: "Water",
    name: "Mudkip",
    base_experience: 62,
    height: 4,
    weight: 76,
  },

  {
    id: 21,
    type: "Steel",
    name: "Magnemite",
    base_experience: 65,
    height: 3,
    weight: 60,
  },
  {
    id: 22,
    type: "Steel",
    name: "Steelix",
    base_experience: 179,
    height: 92,
    weight: 4000,
  },
  {
    id: 23,
    type: "Steel",
    name: "Scizor",
    base_experience: 175,
    height: 18,
    weight: 1180,
  },
  {
    id: 24,
    type: "Steel",
    name: "Skarmory",
    base_experience: 163,
    height: 17,
    weight: 505,
  },
  {
    id: 25,
    type: "Steel",
    name: "Mawile",
    base_experience: 133,
    height: 6,
    weight: 115,
  },
  {
    id: 26,
    type: "Steel",
    name: "Metagross",
    base_experience: 270,
    height: 16,
    weight: 5500,
  },
  {
    id: 27,
    type: "Steel",
    name: "Empoleon",
    base_experience: 239,
    height: 17,
    weight: 845,
  },
  {
    id: 28,
    type: "Steel",
    name: "Lucario",
    base_experience: 184,
    height: 12,
    weight: 540,
  },
  {
    id: 29,
    type: "Steel",
    name: "Excadrill",
    base_experience: 178,
    height: 7,
    weight: 404,
  },
  {
    id: 30,
    type: "Steel",
    name: "Aegislash",
    base_experience: 250,
    height: 17,
    weight: 530,
  },

  {
    id: 31,
    type: "Dragon",
    name: "Dratini",
    base_experience: 60,
    height: 18,
    weight: 33,
  },
  {
    id: 32,
    type: "Dragon",
    name: "Dragonair",
    base_experience: 147,
    height: 40,
    weight: 165,
  },
  {
    id: 33,
    type: "Dragon",
    name: "Dragonite",
    base_experience: 270,
    height: 22,
    weight: 2100,
  },
  {
    id: 34,
    type: "Dragon",
    name: "Kingdra",
    base_experience: 243,
    height: 18,
    weight: 152,
  },
  {
    id: 35,
    type: "Dragon",
    name: "Flygon",
    base_experience: 234,
    height: 20,
    weight: 820,
  },
  {
    id: 36,
    type: "Dragon",
    name: "Altaria",
    base_experience: 172,
    height: 11,
    weight: 206,
  },
  {
    id: 37,
    type: "Dragon",
    name: "Garchomp",
    base_experience: 270,
    height: 19,
    weight: 950,
  },
  {
    id: 38,
    type: "Dragon",
    name: "Haxorus",
    base_experience: 270,
    height: 18,
    weight: 1055,
  },
  {
    id: 39,
    type: "Dragon",
    name: "Hydreigon",
    base_experience: 270,
    height: 18,
    weight: 1600,
  },
  {
    id: 40,
    type: "Dragon",
    name: "Salamence",
    base_experience: 270,
    height: 15,
    weight: 1026,
  },

  {
    id: 41,
    type: "Fairy",
    name: "Clefairy",
    base_experience: 113,
    height: 6,
    weight: 75,
  },
  {
    id: 42,
    type: "Fairy",
    name: "Jigglypuff",
    base_experience: 95,
    height: 5,
    weight: 55,
  },
  {
    id: 43,
    type: "Fairy",
    name: "Togepi",
    base_experience: 49,
    height: 3,
    weight: 15,
  },
  {
    id: 44,
    type: "Fairy",
    name: "Marill",
    base_experience: 88,
    height: 4,
    weight: 85,
  },
  {
    id: 45,
    type: "Fairy",
    name: "Ralts",
    base_experience: 40,
    height: 4,
    weight: 66,
  },
  {
    id: 46,
    type: "Fairy",
    name: "Mawile",
    base_experience: 133,
    height: 6,
    weight: 115,
  },
  {
    id: 47,
    type: "Fairy",
    name: "Gardevoir",
    base_experience: 233,
    height: 16,
    weight: 484,
  },
  {
    id: 48,
    type: "Fairy",
    name: "Azumarill",
    base_experience: 189,
    height: 8,
    weight: 285,
  },
  {
    id: 49,
    type: "Fairy",
    name: "Sylveon",
    base_experience: 184,
    height: 10,
    weight: 235,
  },
  {
    id: 50,
    type: "Fairy",
    name: "Florges",
    base_experience: 248,
    height: 11,
    weight: 100,
  },
];
